# Render deployment configuration
services:
  - type: web
    name: cold-calls-dialer
    env: ruby
    plan: starter
    runtime: ruby-3.1
    buildCommand: |
      gem install bundler -v '~> 2.0'
      bundle install --without development test
    startCommand: bundle exec puma -p $PORT -e production
    envVars:
      - key: RACK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: INFO
      - key: twilio_account_sid
        sync: false
      - key: twilio_account_token
        sync: false
      - key: twilio_app_id
        sync: false
      - key: twilio_caller_id
        sync: false
      - key: twilio_queue_name
        value: CustomerService
      - key: twilio_dqueue_url
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: anycallerid
        value: none
